import {
  BarChart3,
  CalendarCheck,
  CalendarDays,
  ClipboardCheck,
  FileBarChart,
  FileText,
  Flag,
  Percent,
  Settings,
  SlidersHorizontal,
  Target,
  Ticket,
  UserCog,
  Users,
  WalletCards,
} from "lucide-react";
import type { Customer, NavItem } from "./types";

export const navItems: NavItem[] = [
  { key: "dashboard", label: "Dashboard", Icon: BarChart3 },
  { key: "employees", label: "NhÃ¢n viÃªn", Icon: UserCog },
  { key: "customers", label: "Khách Hàng", Icon: Users },
  { key: "pricing", label: "Bảng Giá", Icon: SlidersHorizontal },
  { key: "contracts", label: "Hợp Đồng", Icon: FileText },
  { key: "tickets", label: "Vé Lẻ", Icon: Ticket },
  { key: "teetime", label: "Golf Teetime", Icon: Flag },
  { key: "line", label: "Golf Line Tập", Icon: Target },
  { key: "coach", label: "Lịch HLV", Icon: CalendarCheck },
  { key: "classes", label: "Lịch Lớp", Icon: CalendarDays },
  { key: "checkin", label: "Check-in/out", Icon: ClipboardCheck },
  { key: "cashbook", label: "Sổ Quỹ", Icon: WalletCards },
  { key: "commission", label: "Hoa Hồng Sale", Icon: Percent },
  { key: "settings", label: "Cài Đặt", Icon: Settings },
  { key: "reports", label: "Báo cáo", Icon: FileBarChart },
];

export type Booking = {
  code: string;
  customerName: string;
  customerCode: string;
  facility: string;
  date: string;
  time: string;
  status: string;
};

export const recentBookings: Booking[] = [
  { code: "BK001", customerName: "Nguyễn Văn A", customerCode: "HV001", facility: "Golf Teetime", date: "07/04/2026", time: "14:00 - 16:00", status: "Đã Xác Nhận" },
  { code: "BK002", customerName: "Trần Thị B", customerCode: "HV002", facility: "Golf Teetime", date: "07/04/2026", time: "15:00 - 16:00", status: "Đã Xác Nhận" },
  { code: "BK003", customerName: "Lê Văn C", customerCode: "HV003", facility: "Golf Line Tập", date: "07/04/2026", time: "16:00 - 17:00", status: "Chờ Xác Nhận" },
  { code: "BK004", customerName: "Phạm Văn D", customerCode: "HV004", facility: "Golf Teetime", date: "07/04/2026", time: "09:00 - 11:00", status: "Đã Xác Nhận" },
  { code: "BK005", customerName: "Hoàng Thị E", customerCode: "HV005", facility: "Golf Line Tập", date: "07/04/2026", time: "10:00 - 11:00", status: "Chờ Xác Nhận" },
];

export const customerRows: Customer[] = [
  {
    code: "HV001",
    name: "Nguyễn Văn A",
    phone: "0901234567",
    email: "nguyenvana@gmail.com",
    gender: "Nam",
    birth: "15/5/1990",
    status: "Hết hạn",
    cards: ["green", "red"],
    registerDate: "15/1/2024",
    endDate: "15/7/2024",
    createdDate: "10/1/2024",
    creator: "Admin",
    debt: "1.500.000 VND",
  },
  {
    code: "HV002",
    name: "Trần Thị B",
    phone: "0901234567s",
    email: "tranthib@gmail.com",
    gender: "Nữ",
    birth: "20/8/1995",
    status: "Còn hạn",
    cards: ["green", "red"],
    registerDate: "1/2/2024",
    endDate: "31/12/2026",
    createdDate: "28/1/2024",
    creator: "Nguyễn Văn Thành",
    debt: "0 VND",
  },
  {
    code: "HV003",
    name: "Lê Văn C",
    phone: "0923456789",
    email: "levanc@gmail.com",
    gender: "Nam",
    birth: "10/12/1988",
    status: "Hết hạn",
    cards: ["red", "red"],
    registerDate: "1/11/2023",
    endDate: "1/2/2024",
    createdDate: "25/10/2023",
    creator: "Admin",
    debt: "2.800.000 VND",
  },
  {
    code: "HV004",
    name: "Phạm Thị D",
    phone: "0934567890",
    email: "phamthid@gmail.com",
    gender: "Nữ",
    birth: "25/3/1992",
    status: "Chưa đăng ký",
    cards: ["amber"],
    registerDate: "---",
    endDate: "---",
    createdDate: "5/3/2024",
    creator: "Trần Minh Hoàng",
    debt: "0 VND",
  },
  {
    code: "HV005",
    name: "Huỳnh Xuân Long",
    phone: "0910070932",
    email: "member5@gmail.com",
    gender: "Nam",
    birth: "6/8/1975",
    status: "Hết hạn",
    cards: ["red"],
    registerDate: "1/6/2023",
    endDate: "1/9/2023",
    createdDate: "20/5/2023",
    creator: "Admin",
    debt: "500.000 VND",
  },
  {
    code: "HV006",
    name: "Phan Ngọc Hà",
    phone: "0310078551",
    email: "member6@gmail.com",
    gender: "Nữ",
    birth: "7/7/1976",
    status: "Chưa đăng ký",
    cards: [],
    registerDate: "---",
    endDate: "---",
    createdDate: "12/2/2024",
    creator: "Lê Thị Mai",
    debt: "0 VND",
  },
  {
    code: "HV007",
    name: "Vũ Hồng Nhất",
    phone: "0510086770",
    email: "member7@gmail.com",
    gender: "Nam",
    birth: "8/8/1977",
    status: "Còn hạn",
    cards: ["green", "red"],
    registerDate: "1/8/2025",
    endDate: "1/8/2026",
    createdDate: "15/7/2025",
    creator: "Nguyễn Văn Thành",
    debt: "0 VND",
  },
  {
    code: "HV008",
    name: "Võ Đức Hiếu",
    phone: "0710094689",
    email: "member8@gmail.com",
    gender: "Nam",
    birth: "9/9/1978",
    status: "Hết hạn",
    cards: ["green", "red"],
    registerDate: "1/9/2022",
    endDate: "1/10/2022",
    createdDate: "20/8/2022",
    creator: "Admin",
    debt: "3.200.000 VND",
  },
  {
    code: "HV009",
    name: "Đặng Hồng Châu",
    phone: "0810102608",
    email: "member9@gmail.com",
    gender: "Nữ",
    birth: "10/10/1979",
    status: "Hết hạn",
    cards: [],
    registerDate: "1/10/2023",
    endDate: "1/1/2024",
    createdDate: "25/9/2023",
    creator: "Trần Minh Hoàng",
    debt: "1.200.000 VND",
  },
  {
    code: "HV010",
    name: "Bùi Trung Đông",
    phone: "0910110527",
    email: "member10@gmail.com",
    gender: "Nam",
    birth: "11/11/1980",
    status: "Hết hạn",
    cards: ["amber"],
    registerDate: "1/11/2024",
    endDate: "1/5/2025",
    createdDate: "28/10/2024",
    creator: "Lê Thị Mai",
    debt: "800.000 VND",
  },
];

export const teetimeSlots: Array<[string, string, string]> = [
  ["06:00", "Trống", "green"],
  ["06:15", "Trống", "green"],
  ["06:30", "Nguyễn Văn A · 4 khách", "orange"],
  ["06:45", "Trống", "green"],
  ["07:00", "Trần Thị B · 2 khách", "orange"],
  ["07:15", "Trống", "green"],
  ["07:30", "Trống", "green"],
  ["07:45", "Lê Văn C · 6 khách", "orange"],
  ["08:00", "Trống", "green"],
  ["08:15", "Trống", "green"],
  ["08:30", "Bảo trì sân", "gray"],
  ["08:45", "Trống", "green"],
];

export const lineSlots = Array.from({ length: 18 }, (_, index) => {
  const status = index % 6 === 0 ? "maintenance" : index % 3 === 0 ? "busy" : "free";
  return {
    name: `Line ${String(index + 1).padStart(2, "0")}`,
    status,
  };
});
